"""add budgets and ai_insights

Revision ID: 9ccba09c3700
Revises: 3ae17e92cd47
Create Date: 2026-06-07 20:56:09.334121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ccba09c3700'
down_revision: Union[str, Sequence[str], None] = '3ae17e92cd47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_insights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('insight_type', sa.String(length=30), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_insights_user_id'), 'ai_insights', ['user_id'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('monthly_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('month_year', sa.String(length=7), nullable=False, comment='Format: yyyy-mm'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_user_id'), 'budgets', ['user_id'], unique=False)
    op.drop_index(op.f('ix_aiInsight_user_id'), table_name='aiInsight')
    op.drop_table('aiInsight')
    op.drop_index(op.f('ix_budget_user_id'), table_name='budget')
    op.drop_table('budget')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('monthly_limit', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('month_year', sa.VARCHAR(length=7), autoincrement=False, nullable=False, comment='Format: yyyy-mm'),
    sa.Column('create_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('budget_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('budget_pkey'))
    )
    op.create_index(op.f('ix_budget_user_id'), 'budget', ['user_id'], unique=False)
    op.create_table('aiInsight',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('insight_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('create_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('aiInsight_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('aiInsight_pkey'))
    )
    op.create_index(op.f('ix_aiInsight_user_id'), 'aiInsight', ['user_id'], unique=False)
    op.drop_index(op.f('ix_budgets_user_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_ai_insights_user_id'), table_name='ai_insights')
    op.drop_table('ai_insights')
    # ### end Alembic commands ###
